<a href="https://colab.research.google.com/github/RamosTor/MineriaDeDatos/blob/main/Conceptos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Primer Parcial

### Introduccion

#### Conceptos

La minería de datos es un conjunto de técnicas y procesos que permiten extraer patrones significativos, tendencias y información útil a partir de grandes volúmenes de datos. Esta práctica se puede considerar un subcampo de la inteligencia artificial y la estadística, y su objetivo principal es transformar datos sin procesar en información comprensible y aplicable.

Ciencia de datos

La ciencia de datos es un campo que combina las matemáticas y la estadística, la programación especializada, los analytics avanzados, la inteligencia artificial IA y el machine learning con conocimientos específicos en la materia para descubrir insights procesables ocultos en los datos de una organización.

Help and Document in IPython

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
# Ejemplo con una función con Docstring
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
# Ejemplo de ayuda de funcion personalizada
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

In [ ]:
from itertools import combinations

IPython Magic Commands

In [5]:
#Sirve para evaluar el desempeño de una expresion en cuanto a tiempo
In [8]: %timeit L = [n ** 2 for n in range(1000)]

39.6 µs ± 613 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
# Con doble porcentaje podemos evaluar el desempeño en cuanto a tiempo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

IPython and Shell Commands

In [10]:
!ls

sample_data


In [11]:
!ls

'Inteligencia Artificial 2a ed espanol.pdf'   sample_data


In [12]:
!pwd

/content


In [14]:
!echo "Hola Mundo"

Hola Mundo


In [15]:
contents = !ls

In [16]:
print(contents)

["'Inteligencia Artificial 2a ed espanol.pdf'   sample_data"]


In [17]:
directory = !pwd

In [18]:
print(directory)

['/content']


In [19]:
type(directory)

IPython.utils.text.SList

In [20]:
message = "hello from Python"

In [21]:
!echo {message}

hello from Python


In [22]:
%cd /content/

/content


In [23]:
%ls

'Inteligencia Artificial 2a ed espanol.pdf'   sample_data/


In [24]:
%cd sample_data/

/content/sample_data


In [25]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [26]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


Understanding Data Types in Python

In [33]:
resut=0
for i in range(100):
  resut+=i
print(resut)

4950


In [35]:
#Importa numpy y renombralo como np
import numpy as np

In [36]:
#Arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [38]:
#Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [39]:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [40]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [41]:
#Cuando el argumento de np.array es una interracion anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [42]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]