<a href="https://colab.research.google.com/github/RamosTor/MineriaDeDatos/blob/main/Conceptos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Primer Parcial

### Introduccion

#### Conceptos

La minería de datos es un conjunto de técnicas y procesos que permiten extraer patrones significativos, tendencias y información útil a partir de grandes volúmenes de datos. Esta práctica se puede considerar un subcampo de la inteligencia artificial y la estadística, y su objetivo principal es transformar datos sin procesar en información comprensible y aplicable.

Ciencia de datos

La ciencia de datos es un campo que combina las matemáticas y la estadística, la programación especializada, los analytics avanzados, la inteligencia artificial IA y el machine learning con conocimientos específicos en la materia para descubrir insights procesables ocultos en los datos de una organización.

Help and Document in IPython

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
# Ejemplo con una función con Docstring
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
# Ejemplo de ayuda de funcion personalizada
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

In [ ]:
from itertools import combinations

IPython Magic Commands

In [ ]:
#Sirve para evaluar el desempeño de una expresion en cuanto a tiempo
In [8]: %timeit L = [n ** 2 for n in range(1000)]

39.6 µs ± 613 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Con doble porcentaje podemos evaluar el desempeño en cuanto a tiempo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
!ls

'Inteligencia Artificial 2a ed espanol.pdf'   sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "Hola Mundo"

Hola Mundo


In [ ]:
contents = !ls

In [ ]:
print(contents)

["'Inteligencia Artificial 2a ed espanol.pdf'   sample_data"]


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/

/content


In [ ]:
%ls

'Inteligencia Artificial 2a ed espanol.pdf'   sample_data/


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


Understanding Data Types in Python

In [ ]:
resut=0
for i in range(100):
  resut+=i
print(resut)

4950


In [1]:
#Importa numpy y renombralo como np
import numpy as np

In [2]:
#Arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
#Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Cuando el argumento de np.array es una interracion anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

Creating Arrays from Scratch

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.random((3, 3))

array([[0.46437487, 0.45284646, 0.29707451],
       [0.51517122, 0.327013  , 0.68394146],
       [0.42625886, 0.29010212, 0.95488453]])

In [10]:
np.random.normal(0, 1, (3, 3))

array([[-1.0740585 ,  1.12558964, -0.85745662],
       [ 0.00706551,  0.0723459 ,  2.72753214],
       [-0.54456944,  0.39763867,  2.30565187]])

In [11]:
np.random.randint(0, 10, (3, 3))

array([[0, 5, 1],
       [1, 3, 1],
       [9, 5, 6]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [17]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional arra

In [18]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [19]:
print("dtype:", x3.dtype)


dtype: int64


In [20]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x1[0]

np.int64(5)

In [23]:
x1[3]

np.int64(3)

In [24]:
x1[-1]

np.int64(9)

In [25]:
x1[-2]

np.int64(7)

In [26]:
x2[0,2]

np.int64(2)

In [28]:
x2[-1,-1]

np.int64(7)

In [29]:
x2[-1,-1]=2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

AnalisisEstadistico Basico con Numpy

In [30]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [31]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [32]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [34]:
mediana = np.median(data)
print(mediana)

3.0


Varianza y Desviación Estándar


In [39]:
varianza =np.var(data)
desviacion_estandar =np.std(data)
print(varianza)
print(desviacion_estandar)

2.0
1.4142135623730951


Generación de Datos Aleatorios


In [36]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

Funciones Estadísticas Adicionales (NumPy)

In [40]:
np.quantile(data, 0.5)

np.float64(3.0)